# Generated by Django 3.1.2 on 2020-10-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
