# Generated by Django 3.1.2 on 2020-10-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_search', '0003_auto_20201006_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='order',
        ),
    ]
