# Generated by Django 3.1.2 on 2020-10-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_search', '0004_auto_20201006_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_search.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='order_search.order'),
            preserve_default=False,
        ),
    ]
